name: Main workflow file

on:
  push:
    branches:
      - main
    
    # To manually trigger the workflow
    workflow_dispatch:

  schedule:
    - cron: "0 */6 * * *" # run every 6 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      - name: Generate RSS feed(s)
        run: mkdir public && python main.py
      
      - name: Deploy to surge.sh
        run: npx surge ./public --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
