name: Main workflow file

on:
  push:
    branches:
      - main
    
    # To manually trigger the workflow
    workflow_dispatch:

  schedule:
    - cron: "0 */3 * * *" # run every 3 hours

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and configure poetry
        run: |
          python -m pip install -U poetry~=1.0
          python -m poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        id: poetry-cache
        uses: actions/cache@v3
        with:
          path: ./.venv
          key: ${{ runner.os }}-venv-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        if: steps.poetry-cache.outputs.cache-hit != 'true'
        run: python -m poetry install
      
      - name: Generate RSS feed
        run: |
          mkdir public
          poetry run python main.py
      
      - name: Deploy to surge.sh
        run: npx surge ./public --domain ${{ secrets.SURGE_DOMAIN }} --token ${{ secrets.SURGE_TOKEN }}
